HUGE refactor

diff --git a/lib/layer/list b/lib/layer/list
--- a/lib/layer/list
+++ b/lib/layer/list
@@ -7,4 +7,145 @@
 # github.com/mattferris/tupper/blob/master/License.txt
 #
 
-exec "$TUP_LIB_DIR/list" layer $@
+set -e
+
+if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
+    echo "error: can't locate common.inc" >&2
+    exit 1
+fi
+
+. "$TUP_LIB_DIR/includes/common.inc"
+
+trap tup_error ERR
+
+
+#
+# print usage
+#
+_usage() {
+    cat <<EOF
+
+usage: $TUP_FRONT_CMD $(basename $0) [ --with-label <label> ] [ --date ] [ --format ] [ --full-id ] [ --help ] [ --id-only ] [ --labels ] [ --long ]
+
+List layers. If --label is specified, list layers labelled with <label>.
+
+Arguments:
+
+    General options:
+
+        --help  Print usage information
+
+    Filter options:
+
+        --with-label  List layers labelled with <label>
+
+    Display options:
+
+        --date     Show creation date and time
+        --format   Show the layer format
+        --full-id  Show full layer IDs instead of partials ones
+        --id-only  Only dislay layer IDs (implies --long)
+        --labels   Show layer labels
+        --long     Equivalent --date --format --labels
+
+EOF
+    exit 1
+}
+
+
+#
+# parse args
+#
+
+tup_getopt_required=()
+tup_getopt_optional=(date format full-id help id-only labels long with-label:)
+while tup_getopt; do
+    case $tup_getopt_name in
+        date) opt_date=1 ;;
+        format) opt_format=1 ;;
+        full-id) opt_full_id=1 ;;
+        help) _usage ;;
+        id-only) opt_id_only=1 ;;
+        labels) opt_labels=1 ;;
+        long) opt_date=1; opt_format=1; opt_labels=1 ;;
+        with-label) opt_with_label=$tup_getopt_value ;;
+    esac
+done
+
+# handle option errors
+tup_error_getopt
+
+# check for missing required options
+if [[ ${#tup_getopt_required[@]} -ge 1 ]]; then
+    _usage
+fi
+
+
+#
+# main
+#
+
+if [[ -t 1 && -z $opt_id_only ]]; then
+
+    if [[ ! -z $opt_full_id ]]; then
+        printf "%-65s" ID
+    else
+        printf "%-13s" ID
+    fi
+
+    if [[ ! -z $opt_date ]]; then
+        printf "%-18s" Date
+    fi
+
+    if [[ ! -z $opt_format ]]; then
+        printf "%-9s" Format
+    fi
+
+    if [[ ! -z $opt_labels ]]; then
+        printf "%-s" Labels
+    fi
+
+    echo
+fi
+
+for i in $(tup_list_layers); do
+    if [[ ! -z "$opt_with_label" ]]; then
+       labels=$(tup_conf get layer $i labels) 
+       matched=0
+       for label in $labels; do
+           if [[ $opt_with_label = $label ]]; then
+               matched=1
+           fi
+       done
+       if [[ $matched = 0 ]]; then
+           continue
+       fi
+    fi
+
+    if [[ ! -z $opt_full_id ]]; then
+        printf "%-65s" $i
+    else
+        printf "%-13s" ${i:0:12}
+    fi
+
+    if [[ ! -z $opt_id_only ]]; then
+        echo
+        continue
+    fi
+
+    if [[ ! -z $opt_date ]]; then
+        printf "%-18s" "$(tup_date $(tup_conf get layer $i date))"
+    fi
+
+    if [[ ! -z $opt_format ]]; then
+        printf "%-9s" "$(tup_conf get layer $i format)"
+    fi
+
+    if [[ ! -z $opt_labels ]]; then
+        printf "%-s" "$(tup_conf get layer $i labels)"
+    fi
+
+    echo
+done
+
+exit 0
diff --git a/lib/layer/verify b/lib/layer/verify
--- a/lib/layer/verify
+++ b/lib/layer/verify
@@ -71,8 +71,7 @@ fi
 #
 
 if ! layerid=$(tup refparse --layer "$ref"); then
-    echo "error: layer doesn't exist: $ref" >&2
-    exit 2
+    tup_error 2 "layer doesn't exist: $ref"
 fi
 
 
@@ -81,30 +80,39 @@ fi
 #
 
 while [[ ! -z "$layerid" ]]; do
+    outid=""
     if [[ $opt_long_id = 1 ]]; then
-        echo -n $layerid
+        outid=$layerid
     else
-        echo -n ${layerid:0:12}
+        outid=${layerid:0:12}
     fi
 
-    fs="$TUP_STORAGE_DIR/layers/$(tup_path $layerid)/fs"
+    layerdir="$TUP_STORAGE_DIR/layers/$(tup_path $layerid)"
+    filesystemid=$(tup_conf get layer $layerid filesystem)
+    fsdir="$TUP_STORAGE_DIR/filesystems/$(tup_path $filesystemid)"
+
     case $(tup_conf get layer $layerid format) in
 
-        plain) sum=$(tup_sum_dir "$fs") ;;
-        squashfs) sum=$(tup_sum_file "$fs") ;;
-        tgz) sum=$(tup_sum_file "$fs") ;;
-        *) echo "error: invalid format for layer: $layerid" >&2; exit 2
+        plain) sum=$(tup_sum_dir "$fsdir") ;;
+        squashfs) sum=$(tup_sum_file "$fsdir") ;;
+        tgz) sum=$(tup_sum_file "$fsdir") ;;
+        *) tup_error 2 "invalid format for layer: $layerid" ;;
 
     esac
 
-    layersum=$(tup_conf get layer $layerid checksum)
-    if [[ $sum = $layersum ]]; then
-        echo -n " ok"
-    else
-        echo -n " failed (expected $layersum, got $sum)"
+    if [[ ! $sum = $filesystemid ]]; then
+        echo "$outid failed (filesystem: expected $filesystem, got $sum)"
+        exit 1
+    fi
+    tup_debug 1 "verified filesystem $filesystemid"
+
+    fullsum=$(tup_sum_dir "$dir")
+    if [[ ! $fullsum = $layerid ]]; then
+        echo "$outid failed (expected $layerid, got $fullsum)"
+        exit 1
     fi
 
-    echo
+    echo "$outid ok"
 
     if [[ $opt_lineage = 1 ]]; then
         layerid=$(tup_conf get layer $layerid parent)
