Tweaks to pathing

diff --git a/usr/lib/tupper/commit b/usr/lib/tupper/commit
--- a/usr/lib/tupper/commit
+++ b/usr/lib/tupper/commit
@@ -17,40 +17,57 @@ if [[ -z "$name" ]]; then
     exit 1
 fi
 
-path="$TUP_IMGDIR/$name"
+path=""
 if [[ "$( echo $name | grep ^/ )" = "$name" ]]; then
     path="$name"
+else
+    path="$TUP_IMGDIR/$name"
 fi
 
-if [[ ! -d "$path" ]]; then
+if [[ ! -e "$path" ]]; then
     echo "error: image doesn't exist: $path" >&2
     exit 1
 fi
 
-cd "$path"
+imgsum=""
+if [[ -d "$path" ]]; then
+    cd "$path"
 
-if [[ ! -d "fs" ]]; then
-    echo "error: nothing to commit: $name" >&2
-    exit 1
+    if [[ ! "$path" = "$name" ]]; then
+        if [[ ! -d "fs" ]]; then
+            echo "error: nothing to commit: $name" >&2
+            exit 1
+        fi
+        cd "fs"
+    fi
+
+    imgsum=$( tar c * | sha1sum | cut -d\  -f1 )
+else
+    imgsum=$( sha1sum "$path" | cut -d\  -f1 )
 fi
 
+cd "$path"
 author="$(whoami)@$(hostname -f)"
 
-fssum=$( cd fs && tar c * | sha1sum | cut -d\  -f1 )
 psum=""
 
-if [[ -f "obj" ]]; then
+if [[ ! "$path" = "$name" && -f "obj" ]]; then
     psum=$(cat obj)
 fi
 
-sum=$( echo "${fssum} ${psum}" | sha1sum | cut -d\  -f1 )
+sum=$( echo "${imgsum} ${psum}" | sha1sum | cut -d\  -f1 )
 
 mkdir -p "$TUP_OBJDIR/layers/$sum"
 if [[ ! -d "$TUP_OBJDIR/tags" ]]; then
     mkdir "$TUP_OBJDIR/tags"
 fi
 
-mv fs "$TUP_OBJDIR/layers/$fssum"
+if [[ ! "$path" = "$name" ]]; then
+    mv fs "$TUP_OBJDIR/layers/$fssum"
+else
+    cp -rp "$path" "$TUP_OBJDIR/layers/$fssum"
+fi
+
 echo $fssum > "$TUP_OBJDIR/layers/$sum/fs"
 echo "$author" > "$TUP_OBJDIR/layers/$sum/author"
 echo "$msg" > "$TUP_OBJDIR/layers/$sum/msg"
