Added option to enable/disable image registration for systemd-nspawn

diff --git a/usr/lib/tupper/set b/usr/lib/tupper/set
--- a/usr/lib/tupper/set
+++ b/usr/lib/tupper/set
@@ -35,6 +35,12 @@ if [[ -z "$opt" ]]; then
         echo "net = $(cat "$TUP_IMGDIR/$name/net")"
     fi
 
+    if [[ -f "$TUP_IMGDIR/$name/register" ]]; then
+        echo "register = yes"
+    else
+        echo "register = no"
+    fi
+
     exit
 
 fi
@@ -46,16 +52,29 @@ fi
 
 case "$opt" in
 
-    "net")
-        echo "$val" > "$TUP_IMGDIR/$name/net"
-        ;;
-
     "ephemeral")
         case "$val" in
             "yes")
                 touch "$TUP_IMGDIR/$name/ephemeral" ;;
             "no")
                 [ -f "$TUP_IMGDIR/$name/ephemeral" ] && rm "$TUP_IMGDIR/$name/ephemeral" ;;
+            *)
+                echo "error: expects a 'yes' or 'no' value" >&2
+                exit 1
+                ;;
+        esac
+        ;;
+
+    "net")
+        echo "$val" > "$TUP_IMGDIR/$name/net"
+        ;;
+
+    "register")
+        case "$val" in
+            "yes")
+                touch "$TUP_IMGDIR/$name/register" ;;
+            "no")
+                [ -f "$TUP_IMGDIR/$name/register" ] && rm "$TUP_IMGDIR/$name/register" ;;
             *)
                 echo "error: expects a 'yes' or 'no' value" >&2
                 exit 1
