Backup commit

diff --git a/lib/image/create b/lib/image/create
--- a/lib/image/create
+++ b/lib/image/create
@@ -40,6 +40,7 @@ Create a new image named <name>, using either layer <ref> or the contents of
 Arguments:
 
     name      The name the image
+
     --help    Print usage information
     --labels  Labels to apply to the image
     --layer   The layer ref to use as the image's filesystem
@@ -50,14 +51,14 @@ EOF
 }
 
 tup_getopt_required=(1)
-tup_getopt_optional=(layer: path: labels:)
+tup_getopt_optional=(help labels: layer: path:)
 while tup_getopt; do
     case $tup_getopt_name in
         1) name=$tup_getopt_value ;;
         help) _usage ;;
         labels) opt_labels=$tup_getopt_value ;;
-        layer) opt_layer=$tup_getopt_layer ;;
-        path) opt_path=$tup_getopt_path ;;
+        layer) opt_layer=$tup_getopt_value ;;
+        path) opt_path=$tup_getopt_value ;;
     esac
 done
 
@@ -84,8 +85,8 @@ if [[ ! -z "$opt_path" && ! -d "$opt_path" ]]; then
     exit 2
 fi
 
-if [[ ! -z "$opt_layer" ]] && ! layerid=$(tup refparse "$opt_layer"); then
-    echo "error: layer doesn't exist: $ref" >&2
+if [[ ! -z "$opt_layer" ]] && ! layerid=$(tup refparse --layer "$opt_layer"); then
+    echo "error: layer doesn't exist: $opt_layer" >&2
     exit 2
 fi
 
@@ -95,17 +96,18 @@ fi
 #
 
 if [[ -z "$layerid" ]]; then
+    tup_debug 1 "creating new layer from path: $opt_path"
     # create the new layer
-    if ! layerid=$(tup layer create "$opt_path" --format squashfs); then
+    if ! layerid=$(tup layer create "$opt_path" --format squashfs | cut -d\  -f3); then
         echo "error: failed to initialize image: $name" >&2
         exit 4
     fi
 else
-    if ! layerid=$(tup refparse layer "$opt_layer"); then
+    tup_debug 1 "using existing layer $layerid"
+    if ! layerid=$(tup refparse --layer "$opt_layer"); then
         echo "error: layer doesn't exist; $opt_layer" >&2
         exit 2
     fi
-    tup_debug 1 "using existing layer $layerid"
 fi
 
 tmpid=$(tup_sum_str $name $(date))
@@ -119,6 +121,7 @@ tup_debug 1 "created temporary image directory $tmpdir"
 
 touch "$tmpdir/conf"
 tup_conf set path "$tmpdir/conf" name $name
+tup_conf set path "$tmpdir/conf" date $(date --iso-8601=seconds)
 tup_conf set path "$tmpdir/conf" volumes $layerid
 
 if [[ ! -z "$opt_labels" ]]; then
@@ -134,12 +137,16 @@ if ! (mkdir -p "$TUP_STORAGE_DIR/images/$pdir"); then
     exit 3
 fi
 
-if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/containers/$pdir/$imageid"); then
+if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/images/$pdir/$imageid"); then
     echo "error: failed to create image dir $TUP_STORAGE_DIR/images/$path" >&2
     exit 3
 fi
 tup_debug 1 "moved $tmpdir to $TUP_STORAGE_DIR/images/$path"
 
-echo "created image $name ($imageid)"
+if [[ -t 1 ]]; then
+    echo -n "created image $name "
+fi
+
+echo $imageid
 
 exit 0
diff --git a/lib/layer/create b/lib/layer/create
--- a/lib/layer/create
+++ b/lib/layer/create
@@ -32,16 +32,20 @@ trap tup_error ERR
 _usage() {
     cat <<EOF
 
-usage: $TUP_FRONT_CMD $(basename $0) <path> [ --help ] [ --labels <label>,... ] [ --format <format> ] [ --squashfs-opts <opts> ] [ --tar-opts <opts> ]
+usage: $TUP_FRONT_CMD $(basename $0) <path> [ --help ] [ --labels <label>,... ] [ --parent <ref> ] [ --plain | --squashfs | --tgz ] [ --squashfs-opts <opts> ] [ --tar-opts <opts> ]
 
 Create a new layer, using <path> as it's filesystem.
 
 Arguments:
 
     path      The path containing the layer's filesystem
-    --format  The format for the filesystem: plain (default), squashfs, or tgz
-    --help    Print usage information
-    --label   Labels to apply to the layer
+
+    --help      Print usage information
+    --labels    Labels to apply to the layer
+    --parent    Set <ref> as the parent of the layer
+    --plain     Save the layer's filesystem as a plain directory
+    --squashfs  Save the layer's filesystem as a squashfs volume (default)
+    --tgz       Save the layer's filesystem as a gzipped tarball
 
     --squashfs-opts
               Options to pass to squashfs
@@ -58,16 +62,21 @@ EOF
 # parse args
 #
 
+format="squashfs"
+
 tup_getopt_required=(1)
-tup_getopt_optional=(help labels: format: squasfs-opts: tar-opts:)
+tup_getopt_optional=(help labels: parent: plain squashfs squashfs-opts: tar-opts: tgz)
 while tup_getopt; do
     case $tup_getopt_name in
         1) path=$tup_getopt_value ;;
-        format) opt_format=$tup_getopt_value ;;
         help) _usage ;;
         labels) opt_labels=$tup_getopt_value ;;
+        parent) opt_parent=$tup_getopt_value ;;
+        plain) format="plain" ;;
+        squashfs) format="squashfs" ;;
         squashfs-opts) opt_squashfs_opts=$tup_getopt_value ;;
         tar-opts) opt_tar_opts=$tup_getopt_value ;;
+        tgz) format="tgz" ;;
     esac
 done
 
@@ -89,6 +98,10 @@ if [[ ! -d "$path" ]]; then
     exit 2
 fi
 
+if [[ ! -z "$opt_parent" ]] && ! parentid=$(tup refparse --layer "$opt_parent"); then
+    echo "error: parent layer doesn't exist: $opt_parent" >&2
+    exit 2
+fi
 
 #
 # create the layer directory
@@ -103,14 +116,10 @@ if ! (mkdir -p "$tmpdir"); then
 fi
 tup_debug 1 "created temporary layer directory $tmpdir"
 
+
 #
 # import filesystem into specified format
 #
-
-format="squashfs"
-if [[ ! -z "$tuparg_format" ]]; then
-    format=$tuparg_format
-fi
 
 touch "$tmpdir/conf"
 
@@ -127,8 +136,8 @@ case $format in
         ;;
 
     squashfs)
-        tup_debug 2 "mksquashfs $path $tmpdir/fs -no-progress $tuparg_squashfs_opts"
-        if ! (mksquashfs "$path" "$tmpdir/fs" -no-progress $tuparg_squashfs_opts 2>&1 >/dev/null); then
+        tup_debug 2 "mksquashfs $path $tmpdir/fs -no-progress $opt_squashfs_opts"
+        if ! (mksquashfs "$path" "$tmpdir/fs" -no-progress $opt_squashfs_opts 2>&1 >/dev/null); then
             echo "error: failed to create squashfs from path: $path" >&2
             exit 3
         fi
@@ -138,8 +147,8 @@ case $format in
         ;;
 
     tgz)
-        tup_debug 2 "tar czf $tmpdir/fs --acls --xattr $tuparg_tar_opts $path"
-        if ! (tar czf "$tmpdir/fs" --acls --xattr $tuparg_tar_opts "$path" 2>&1 >/dev/null); then
+        tup_debug 2 "tar czf $tmpdir/fs --acls --xattrs $opt_tar_opts $path"
+        if ! (tar czf "$tmpdir/fs" --acls --xattrs $opt_tar_opts "$path" 2>&1 >/dev/null); then
             echo "error: failed to create tarball from path: $path" >&2
             exit 3
         fi
@@ -158,8 +167,12 @@ esac
 tup_conf set path "$tmpdir/conf" checksum $fssum
 tup_conf set path "$tmpdir/conf" date $(date --iso-8601=seconds)
 
-if [[ ! -z "$tuparg_labels" ]]; then
-    tup_conf set path "$tmpdir/conf" labels $(echo $tuparg_labels | tr , \ )
+if [[ ! -z "$opt_labels" ]]; then
+    tup_conf set path "$tmpdir/conf" labels $(echo $opt_labels | tr , \ )
+fi
+
+if [[ ! -z "$parentid" ]]; then
+    tup_conf set path "$tmpdir/conf" parent $parentid
 fi
 
 layerid=$(tup_sum_dir "$tmpdir")
@@ -179,5 +192,10 @@ if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/layers/$pdir/$layerid"); then
 fi
 tup_debug 1 "moved $tmpdir to $TUP_STORAGE_DIR/layers/$path"
 
-echo "created layer $layerid"
+if [[ -t 1 ]]; then
+    echo -n "created layer "
+fi
+
+echo $layerid
+
 exit 0
diff --git a/lib/layer/destroy b/lib/layer/destroy
--- a/lib/layer/destroy
+++ b/lib/layer/destroy
@@ -25,18 +25,13 @@ trap tup_error ERR
 _usage() {
     cat <<EOF
 
-usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --container | --image | --layer | --volume ] [ --help ]
+usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --help ]
 
-Show object details.
+Destroy a layer.
 
 Arguments:
 
-    ref     The object ID to show
-
-    --container  <ref> refers to a container ID
-    --image      <ref> refers to an image ID
-    --layer      <ref> refers to a layer ID
-    --volume     <ref> refers to a volume ID
+    ref     The layer to destory
 
     --help  Print usage information
 
@@ -49,38 +44,21 @@ EOF
 # parse args
 #
 
-opt_type="container"
-
 tup_getopt_required=(1)
-tup_getopt_optional=(container image layer volume help)
+tup_getopt_optional=(help)
 while tup_getopt; do
     case $tup_getopt_name in
         1) ref=$tup_getopt_value ;;
-        container) opt_type="container" ;;
         help) _usage ;;
-        image) opt_type="container" ;;
-        layer) opt_type="layer" ;;
-        volume) opt_type="volume" ;;
     esac
 done
 
 # handle getopt errors
 tup_error_getopt
 
-# check for missing required options
+# check for missing required args
 if [[ ${#tup_getopt_required[@]} -ge 1 ]]; then
     _usage
-fi
-
-
-#
-# prerequisites
-#
-
-# resolve object ID
-if ! objid=$(tup refparse --$opt_type "$ref"); then
-    echo "error: $opt_type doesn't exist: $ref" >&2
-    exit 2
 fi
 
 
@@ -88,6 +66,20 @@ fi
 # main
 #
 
-tup_conf show $opt_type $objid
+if ! layerid=$(tup refparse --layer "$ref"); then
+    echo "error: layerid doesn't exist: $ref" >&2
+    exit 2
+fi
+
+if ! (rm -r "$TUP_STORAGE_DIR/layers/$(tup_path $layerid)"); then
+    echo "error: failed to destroy layer: $layerid" >&2
+    exit 3
+fi
+
+if [[ -t 1 ]]; then
+    echo -n "destroyed layer "
+fi
+
+echo $layerid
 
 exit 0
