Improved error/debug output, container upper layers now stick around unless using --ephemeral

diff --git a/lib/container/commit b/lib/container/commit
--- a/lib/container/commit
+++ b/lib/container/commit
@@ -10,14 +10,14 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: container commit: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    tup_debug 1 "cleaning up"
+    tup_debug 1 "container commit: cleaning up"
     if [[ ! -z "$tmpdir" && -d "$tmpdir" ]]; then
         rm -r "$tmpdir" 2>&1 >/dev/null
     fi
@@ -32,17 +32,20 @@ trap tup_error ERR
 _usage() {
     cat <<EOF
 
-usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --labels <label>,... | --extra-labels >label>,... ] [ --help ]
+usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --plain | --squashfs | --tgz ] [ --labels <label>,... | --extra-labels <label>,... ] [ --help ]
 
-Mount a volume.
+Commit changes made in the container.
 
 Arguments:
 
-    ref             The source of the volume
+    ref             The container to commit
 
     --help          Print usage information
     --extra-labels  Additional labels for the layer
     --labels        Override labels assigned to the volume
+    --plain         Commit volume in plain format
+    --squashfs      Commit volume in squashfs format
+    --tgz           Commit volume in tgz format
 
 EOF
     exit 1
@@ -54,13 +57,16 @@ EOF
 #
 
 tup_getopt_required=(1)
-tup_getopt_optional=(help extra-labels: labels:)
+tup_getopt_optional=(help extra-labels: labels: plain squashfs tgz)
 while tup_getopt; do
     case $tup_getopt_name in
         1) ref=$tup_getopt_value ;;
-        extra-labels) opt_extra_labels=$tup_getopt_value ;;
-        labels) opt_labels=$tup_getopt_value ;;
+        extra-labels) opt_args="$opt_args --extra-labels $tup_getopt_value" ;;
         help) _usage ;;
+        labels) opt_args="$opt_args --labels $tup_getopt_value" ;;
+        plain) opt_args="$opt_args --plain" ;;
+        squashfs) opt_args="$opt_args --squashfs" ;;
+        tgz) opt_args="$opt_args --tgz" ;;
     esac
 done
 
@@ -78,70 +84,17 @@ fi
 #
 
 if ! containerid=$(tup refparse --container "$ref"); then
-    tup_error 2 "container doesn't exist: $ref"
+    tup_error 2 "container commit: container doesn't exist: $ref"
 fi
 
-if [[ ! -z "$opt_extra_labels" && ! -z "$opt_labels" ]]; then
-    tup_error 2 "only one of --extra-labels and --labels must be specified"
+volumeid=$(tup_conf get container $containerid volume)
+if [[ -z $volumeid ]]; then
+    tup_error 2 "container commit: container doesn't have an active volume"
 fi
 
-
-#
-# main
-#
-
-name=$(tup_conf get container $containerid name)
-
-volumes=$(tup_conf get container $containerid volumes)
-layers=($(tup_conf get container $containerid layers))
-for vol in $volumes; do
-    volume=(${vol/:/ /})
-    if ! layerid=$(tup volume commit ${volume[0]}); then
-        layers=(${layers[@]} $layerid:${volume[1]})
-    fi
-done
-
-if [[ ${#layers[@]} = 0 ]]; then
-    tup_error 2 "container doesn't have any layers or volumes"
+if ! layerid=$(tup volume commit $volumeid $opt_args); then
+    tup_error 2 "container commit: failed to commit changes in container: $ref"
 fi
 
-labels=$(tup_conf get container $containerid labels)
-if [[ ! -z "$opt_extra_labels" ]]; then
-    opt_extra_labels=$(echo -n "$opt_extra_labels" | tr , \ )
-    labels="$labels $opt_extra_labels"
-elif [[ ! -z "$opt_labels" ]]; then
-    labels=$opt_labels
-fi
-
-if [[ ! -z "$labels" ]]; then
-    labels="--labels $(echo -n "$labels" | tr \  ,)"
-fi
-
-parent=$(tup_conf get container $containerid image)
-if [[ ! -z "$parent" ]]; then
-    parent="--parent $parent"
-fi
-
-boot=$(tup_conf get container $containerid boot)
-if [[ ! -z "$boot" ]]; then
-    boot="--boot"
-fi
-
-entrypoint=$(tup_conf get container $containerid entrypoint)
-if [[ ! -z "$entrypoint" ]]; then
-    entrypoint="--entrypoint \"$entrypoint\""
-fi
-
-layersarg=${layers[@]}
-tup_debug 2 "tup image create "$name" --layers ${layersarg/ /:/} $labels $parent $boot $entrypoint"
-if ! imageid=$(tup image create "$name" --layers ${layersarg/ /:/} $labels $parent $boot $entrypoint 2>/dev/null); then
-    tup_error 3 "failed to create image: $imageid"
-fi
-
-if [[ -t 1 ]]; then
-    echo -n "committed container as image "
-fi
-
-echo $imageid
-
-exit 0
+tup_conf set container $containerid layers $layerid:/
+tup_conf unset container $containerid volume
diff --git a/lib/container/create b/lib/container/create
--- a/lib/container/create
+++ b/lib/container/create
@@ -10,14 +10,14 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: container create: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    tup_debug 1 "cleaning up"
+    tup_debug 1 "container create: cleaning up"
     if [[ ! -z "$tmpdir" && -d "$tmpdir" ]]; then
         rm -r "$tmpdir" 2>&1 >/dev/null
     fi
@@ -89,7 +89,7 @@ fi
 
 # does the referenced image exist?
 if ! imageid=$(tup refparse --image "$image"); then
-    tup_error 2 "image doesn't exist: $image"
+    tup_error 2 "container create: image doesn't exist: $image"
 fi
 
 containerid=$(tup_sum_str "$name $imageid")
@@ -97,7 +97,7 @@ tmpdir="$TUP_STORAGE_DIR/staging/$containerid"
 
 # does a container with this name already exist?
 if [[ -d "$TUP_STORAGE_DIR/containers/$containerid" ]]; then
-    tup_error 2 "container already exists: $name"
+    tup_error 2 "container create: container already exists: $name"
 fi
 
 #
@@ -105,7 +105,7 @@ fi
 #
 
 if ! (mkdir -p "$tmpdir"); then
-    tup_error 3 "failed to create container directory: $tmpdir"
+    tup_error 3 "container create: failed to create container directory: $tmpdir"
 fi
 
 touch "$tmpdir/conf"
@@ -134,11 +134,11 @@ path=$(tup_path $containerid)
 pdir=$(dirname $path);
 
 if ! (mkdir -p "$TUP_STORAGE_DIR/containers/$pdir"); then
-    tup_error 3 "failed to create container parent directory: $TUP_STORAGE_DIR/containers/$pdir"
+    tup_error 3 "container create: failed to create container parent directory: $TUP_STORAGE_DIR/containers/$pdir"
 fi
 
 if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/containers/$pdir"); then
-    tup_error 3 "failed to create container dir $TUP_STORAGE_DIR/containers/$path"
+    tup_error 3 "container create: failed to create container dir $TUP_STORAGE_DIR/containers/$path"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/container/destroy b/lib/container/destroy
--- a/lib/container/destroy
+++ b/lib/container/destroy
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: container destroy: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -67,11 +67,11 @@ fi
 #
 
 if ! containerid=$(tup refparse --container "$ref"); then
-    tup_error 2 "container doesn't exist: $ref"
+    tup_error 2 "container create: container doesn't exist: $ref"
 fi
 
 if ! (rm -r "$TUP_STORAGE_DIR/containers/$(tup_path $containerid)"); then
-    tup_error 3 "failed to destroy container: $containerid"
+    tup_error 3 "container create: failed to destroy container: $containerid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/container/run b/lib/container/run
--- a/lib/container/run
+++ b/lib/container/run
@@ -10,18 +10,26 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: container run: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    if [[ ! -z $volumeid ]]; then
-        tup volume destroy $volumeid
+    if [[ ! -z $mntdir && -f "$mntdir/../bindmounts" ]]; then
+        for i in $(cat "$mntdir/../bindmounts"); do
+            umount "$i"
+        done
+    fi
+    if [[ $opt_epheneral != 1 ]]; then
+        return
     fi
     if [[ ! -z $upperid ]]; then
         tup volume destroy $upperid
+    fi
+    if [[ ! -z $volumeid ]]; then
+        tup volume destroy $volumeid
     fi
 }
 trap _cleanup EXIT KILL
@@ -33,19 +41,21 @@ trap _cleanup EXIT KILL
 _usage() {
     cat <<EOF
 
-usage: $TUP_FRONT_CMD $(basename $0) <ref> <cmd> [ --copy <src>:<dest> ] [ --existing | --new ] [ --help ]
+usage: $TUP_FRONT_CMD $(basename $0) <ref> <cmd> [ --bind <src>:<dest> ] [ --copy <src>:<dest> ] [ --existing | --new [ --ephemeral ] ] [ --help ]
 
 Run a command in an instance of container <ref>.
 
 Arguments:
 
-    cmd         The command to run in the container
-    ref         The ID of the container to run the command in
+    cmd          The command to run in the container
+    ref          The ID of the container to run the command in
 
-    --copy      Copy files from the host (<src>) into the container (<dest>)
-    --existing  Run the command in an existing instance of the container
-    --help      Print usage information
-    --new       Run the command in a new (temporary) instances of the container (default)
+    --bind       Bind mount a portion of the host filesystem <src> in the container under <dest>
+    --copy       Copy files from <src> on the host into the container at <dest>
+    --ephemeral  Destroy all changes when container exits (only valid with --new)
+    --existing   Run the command in an existing instance of the container
+    --help       Print usage information
+    --new        Run the command in a new (temporary) instance of the container (default)
 
 EOF
     exit 1
@@ -59,15 +69,17 @@ EOF
 opt_run_cmd="tup_mechanism_run_new"
 
 tup_getopt_required=(1 2)
-tup_getopt_optional=(copy: existing help new systemd-nspawn)
+tup_getopt_optional=(bind: copy: ephemeral existing help new systemd-nspawn)
 while tup_getopt; do
     case $tup_getopt_name in
         1) ref=$tup_getopt_value ;;
         2) opt_cmd=$tup_getopt_value ;;
-        existing) opt_run_cmd="tup_mechanism_run_existing" ;;
+        bind) opt_bind=$tup_getopt_value ;;
+        copy) opt_copy=$tup_getopt_value ;;
+        ephemeral) opt_ephemeral=1 ;;
+        existing) opt_existing=1; opt_run_cmd="tup_mechanism_run_existing" ;;
         help) _usage ;;
         image) image=$tup_getopt_value ;;
-        copy) opt_copy=$tup_getopt_value ;;
         new) opt_run_cmd="tup_mechanism_run_new" ;;
         systemd-nspawn) opt_mechanism=$tup_getopt_name ;;
     esac
@@ -88,7 +100,7 @@ fi
 
 # does the referenced container exist?
 if ! containerid=$(tup refparse --container "$ref"); then
-    tup_error 2 "container doesn't exist: $ref"
+    tup_error 2 "container run: container doesn't exist: $ref"
 fi
 
 # are there bindings for the specified mechanism?
@@ -100,35 +112,52 @@ fi
 
 binding=""
 for path in ${TUP_BINDINGS_PATH/:/ }; do
-    tup_debug 2 "searching for mechanism bindings in $path"
+    tup_debug 2 "container run: searching for mechanism bindings in $path"
     if [[ -f "$path/$mechanism" ]]; then
         binding="$path/$mechanism"
     fi
 done
 
-if [[ -z "$binding" ]]; then
-    tup_error 3 "unable to locate bindings for specified mechanism: $mechanism"
+if [[ -z $binding ]]; then
+    tup_error 3 "container run: unable to locate bindings for specified mechanism: $mechanism"
 fi
 
 . "$binding"
+
+# if we got --ephemeral, check that --new was also 
+if [[ $opt_ephemeral == 1 && ! -z $opt_existing ]]; then
+    tup_error 1 "container run: --ephemeral can only be specified if using --new"
+fi
 
 
 #
 # main
 #
 
+if [[ $opt_ephemeral != 1 ]]; then
+    tmpupperid=$(tup_conf get container $containerid volume)
+    if [[ ! -z $tmpupperid ]] && (tup volume show $tmpupperid) 2>&1 >/dev/null; then
+        upperid=$tmpupperid
+        tup_debug 2 "container run: using existing upper layer $upperid"
+    fi
+fi
+
 # prepare root filesystem
 for i in $(tup_conf get container $containerid layers); do
     layer=(${i/:/ })
     if [[ ${layer[1]} = "/" ]]; then
         if ! lowerids=$(tup layer mount ${layer[0]} --lineage); then
-            tup_error 4 "failed to mount read-only filesystem for container: $containerid"
+            tup_error 4 "container run: failed to mount read-only filesystem for container: $containerid"
         fi
-        if ! upperid=$(tup volume create --empty); then
-            tup_error 4 "failed to create read-write filesystem for container: $containerid"
+        if [[ -z $upperid ]]  && ! upperid=$(tup volume create --empty); then
+            tup_error 4 "container run: failed to create read-write filesystem for container: $containerid"
         fi
         if ! volumeid=$(echo -e "$lowerids\n$upperid" | tup volume unify --stdin --read-write); then
-            tup_error 4 "failed to create overlay for container: $containerid"
+            case $? in
+                0) ;;
+                100) ;;
+                *) tup_error 4 "container run: failed to create overlay for container: $containerid" ;;
+            esac
         fi
         tup_conf set container $containerid volume $upperid
     fi
@@ -136,16 +165,30 @@ done
 
 mntdir="$TUP_STORAGE_DIR/volumes/$(tup_path $volumeid)/mount"
 
+# process bind mounts
+for i in $opt_bind; do
+    path=(${i/:/ /})
+    tup_debug 2 "container run: mounting source ${path[0]} in ${path[1]}"
+    if [[ ! -d "${path[0]}" ]]; then
+        tup_error 2 "container run: source doesn't exist or is not a directory ${path[0]}"
+    fi
+    mkdir -p "$mntdir/${path[1]}"
+    if ! mount --bind "${path[0]}" "$mntdir/${path[1]}"; then
+        tup_error 4 "container run: failed to bind mount ${path[0]} to ${path[1]}"
+    fi
+    echo "$mntdir/${path[1]}" >> "$mntdir/../bindmounts"
+done
+
 # copy external sources
 for i in $opt_copy; do
     path=(${i/:/ })
-    tup_debug 2 "copying source ${path[0]} to ${path[1]}"
+    tup_debug 2 "container run: copying source ${path[0]} to ${path[1]}"
     if [[ ! -d "${path[0]}" ]]; then
-        tup_error 2 "source doesn't exist or is not a directory ${path[0]}"
+        tup_error 2 "container run: source doesn't exist or is not a directory ${path[0]}"
     fi
     mkdir -p "$mntdir/${path[1]}"
     if ! cp -rp "${path[0]}" "$mntdir/${path[1]}"; then 
-        tupe_error 4 "failed to copy ${path[0]} to ${path[1]}"
+        tup_error 4 "container run: failed to copy ${path[0]} to ${path[1]}"
     fi
 done
 
diff --git a/lib/container/start b/lib/container/start
--- a/lib/container/start
+++ b/lib/container/start
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: container start: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -82,7 +82,7 @@ fi
 
 # does the referenced container exist?
 if ! containerid=$(tup refparse --container "$ref"); then
-    tup_error 2 "container doesn't exist: $ref"
+    tup_error 2 "container start: container doesn't exist: $ref"
 fi
 
 # are there bindings for the specified mechanism?
@@ -101,7 +101,7 @@ for path in ${TUP_BINDINGS_PATH/:/ }; do
 done
 
 if [[ -z "$binding" ]]; then
-    tup_error 3 "unable to locate bindings for specified mechanism: $mechanism"
+    tup_error 3 "container start: unable to locate bindings for specified mechanism: $mechanism"
 fi
 
 . "$binding"
@@ -116,13 +116,13 @@ for i in $(tup_conf get container $containerid layers); do
     layer=(${i/:/ })
     if [[ ${layer[1]} = "/" ]]; then
         if ! lowerids=$(tup layer mount ${layer[0]} --lineage); then
-            tup_error 4 "failed to mount read-only filesystem for container: $containerid"
+            tup_error 4 "container start: failed to mount read-only filesystem for container: $containerid"
         fi
         if ! upperid=$(tup volume create --empty); then
-            tup_error 4 "failed to create read-write filesystem for container: $containerid"
+            tup_error 4 "container start: failed to create read-write filesystem for container: $containerid"
         fi
         if ! volumeid=$(echo -e "$lowerids\n$upperid" | tup volume unify --stdin --read-write); then
-            tup_error 4 "failed to create overlay for container: $containerid"
+            tup_error 4 "container start: failed to create overlay for container: $containerid"
         fi
         tup_conf set container $containerid volume $upperid
     fi
@@ -133,7 +133,7 @@ export TUP_MECHANISM_ROOT="$TUP_STORAGE_DIR/volumes/$(tup_path $volumeid)/mount"
 export TUP_MECHANISM_BOOT=$(tup_conf get container $containerid boot)
 export TUP_MECHANISM_NAME=$(tup_conf get container $containerid name)
 if ! (tup_mechanism_start); then
-    tup_error 4 "failed to start container: $containerid"
+    tup_error 4 "container start: failed to start container: $containerid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/image/create b/lib/image/create
--- a/lib/image/create
+++ b/lib/image/create
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: image create: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -89,11 +89,11 @@ fi
 if [[ ! -z $opt_layers && ! -z $opt_volumes ]] \
    || [[ ! -z $opt_path && ! -z $opt_layers ]] \
    || [[ ! -z $opt_path && ! -z $opt_volumes ]]; then
-    tup_error 1 "only one of --layer, --path, or --volume can be specified"
+    tup_error 1 "image create: only one of --layer, --path, or --volume can be specified"
 fi
 
 if [[ ! -z $opt_layer_format && ! -z $opt_layers ]]; then
-    echo "warning: using --${opt_layer_format} with --layers doesn't make sense, ignoring" >&2
+    tup_notice "image create: using --${opt_layer_format} with --layers doesn't make sense, ignoring"
 fi
 
 #
@@ -101,15 +101,15 @@ fi
 #
 
 if [[ ! -z $opt_path && ! -d "$opt_path" ]]; then
-    tup_error 2 "path doesn't exist: $opt_path"
+    tup_error 2 "image create: path doesn't exist: $opt_path"
 fi
 
 if [[ ! -z $opt_parent ]] && ! parentid=$(tup refparse --image "$opt_parent"); then
-    tup_error 2 "parent image doesn't exist: $opt_parent"
+    tup_error 2 "image create: parent image doesn't exist: $opt_parent"
 fi
 
 if [[ ! -z $opt_boot && ! -z $opt_entrypoint ]]; then
-    tup_error 2 "only one of --boot or --entrypoint can be specified"
+    tup_error 2 "image create: only one of --boot or --entrypoint can be specified"
 fi
 
 
@@ -121,9 +121,9 @@ tmpid=$(tup_sum_str $name $(date))
 tmpdir="$TUP_STORAGE_DIR/staging/$tmpid"
 
 if ! (mkdir -p "$tmpdir"); then
-    tup_error 3 "failed to create temporary image directory: $tmpdir"
+    tup_error 3 "image create: failed to create temporary image directory: $tmpdir"
 fi
-tup_debug 1 "created temporary image directory $tmpdir"
+tup_debug 1 "image create: created temporary image directory $tmpdir"
 
 touch "$tmpdir/conf"
 tup_conf set path "$tmpdir/conf" author "$TUP_USER_NAME <$TUP_USER_EMAIL>"
@@ -132,7 +132,7 @@ tup_conf set path "$tmpdir/conf" date $(date --iso-8601=seconds)
 
 if [[ ! -z $opt_path ]]; then
 
-    tup_debug 1 "creating new layer from path: $opt_path"
+    tup_debug 1 "image create: creating new layer from path: $opt_path"
 
     if [[ ! -z $opt_layer_format ]]; then
         opt_layer_format="--$opt_layer_format"
@@ -140,7 +140,7 @@ if [[ ! -z $opt_path ]]; then
 
     # create the new layer
     if ! layerid=$(tup layer create --path "$opt_path" $opt_layer_format); then
-        tup_error 4 "failed to initialize image: $name"
+        tup_error 4 "image create: failed to initialize image: $name"
     fi
 
     tup_conf set path "$tmpdir/conf" layers $layerid:/
@@ -155,7 +155,7 @@ elif [[ ! -z $opt_layers ]]; then
             layer=(${i/:/ })
             tup_debug 2 "image create: checking layer ${layer[0]}:${layer[1]}"
             if ! layerid=$(tup refparse --layer "${layer[0]}"); then
-                tup_error 2 "layer doesn't exist: ${layer[0]}"
+                tup_error 2 "image create: layer doesn't exist: ${layer[0]}"
             fi
             if [[ ${layer[1]} = "/" ]]; then
                 hasroot=1
@@ -165,7 +165,7 @@ elif [[ ! -z $opt_layers ]]; then
     fi
 
     if [[ $hasroot = 0 ]]; then
-        tup_error 2 "no root filesystem specified"
+        tup_error 2 "image create: no root filesystem specified"
     fi
 
     tup_conf set path "$tmpdir/conf" layers "${layers[@]}"
@@ -177,7 +177,7 @@ if [[ ! -z $parentid ]]; then
 fi
 
 if [[ ! -z $opt_labels ]]; then
-    tup_conf set path "$tmpdir/conf" labels ${labels/,/ }
+    tup_conf set path "$tmpdir/conf" labels ${opt_labels/,/ }
 fi
 
 if [[ ! -z $opt_boot ]]; then
@@ -193,13 +193,13 @@ path=$(tup_path "$imageid")
 pdir=$(dirname $path);
 
 if ! (mkdir -p "$TUP_STORAGE_DIR/images/$pdir"); then
-    tup_error 3 "failed to create images parent directory: $TUP_STORAGE_DIR/images/$pdir"
+    tup_error 3 "image create: failed to create images parent directory: $TUP_STORAGE_DIR/images/$pdir"
 fi
 
 if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/images/$pdir/$imageid"); then
-    tup_error 3 "failed to create image dir $TUP_STORAGE_DIR/images/$path"
+    tup_error 3 "image create: failed to create image dir $TUP_STORAGE_DIR/images/$path"
 fi
-tup_debug 1 "moved $tmpdir to $TUP_STORAGE_DIR/images/$path"
+tup_debug 1 "image create: moved $tmpdir to $TUP_STORAGE_DIR/images/$path"
 
 if [[ -t 1 ]]; then
     echo -n "created image $name "
diff --git a/lib/image/destroy b/lib/image/destroy
--- a/lib/image/destroy
+++ b/lib/image/destroy
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: image destroy: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -67,11 +67,11 @@ fi
 #
 
 if ! imageid=$(tup refparse --image "$ref"); then
-    tup_error 2 "image doesn't exist: $ref"
+    tup_error 2 "image destroy: image doesn't exist: $ref"
 fi
 
 if ! (rm -r "$TUP_STORAGE_DIR/images/$(tup_path $imageid)"); then
-    tup_error 3 "failed to destroy images: $imageid"
+    tup_error 3 "image destroy: failed to destroy images: $imageid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/image/lineage b/lib/image/lineage
--- a/lib/image/lineage
+++ b/lib/image/lineage
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: image lineage: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -71,8 +71,7 @@ fi
 #
 
 if ! imageid=$(tup refparse --image "$ref"); then
-    echo "error: image doesn't exist: $ref" >&2
-    exit 2
+    tup_error 2 "image lineage: image doesn't exist: $ref"
 fi
 
 
diff --git a/lib/image/verify b/lib/image/verify
--- a/lib/image/verify
+++ b/lib/image/verify
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: image verify: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -71,7 +71,7 @@ fi
 #
 
 if ! imageid=$(tup refparse --image "$ref"); then
-    tup_error 2 "image doesn't exist: $ref"
+    tup_error 2 "image verify: image doesn't exist: $ref"
 fi
 
 
@@ -91,15 +91,14 @@ while [[ ! -z "$imageid" ]]; do
         parts=(${layer/:/ /})
         layerid=${parts[0]}
         if ! (tup layer verify "$layerid" >&1 >/dev/null); then
-            tup_error 4 "failed (layer $layerid failed verification)"
+            tup_error 4 "image verify: failed (layer $layerid failed verification)"
         fi
-        tup_debug 1 "verified layer $layerid"
+        tup_debug 1 "image verify: verified layer $layerid"
     done
 
     imagesum=$(tup_sum_dir "$TUP_STORAGE_DIR/images/$(tup_path $imageid)")
     if [[ ! $imagesum = $imageid ]]; then
-        echo "$outid failed (expected $imageid, got $imagesum)"
-        exit 1 
+        tup_error 1 "image verify: $outid failed (expected $imageid, got $imagesum)"
     fi
 
     echo "$outid ok"
diff --git a/lib/layer/create b/lib/layer/create
--- a/lib/layer/create
+++ b/lib/layer/create
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer create: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -93,21 +93,21 @@ fi
 #
 
 if [[ ! -z "$opt_filesystem" && ! -z "$opt_path" ]]; then
-    tup_error 2 "only one of --filesystem or --path can be specified"
+    tup_error 2 "layer create: only one of --filesystem or --path can be specified"
 elif [[ -z "$opt_filesystem" && -z "$opt_path" ]]; then
-    tup_error 2 "one of --filesystem or --path must be specified"
+    tup_error 2 "layer create: one of --filesystem or --path must be specified"
 fi
 
 if [[ ! -z "$opt_path" && ! -d "$opt_path" ]]; then
-    tup_error 2 "path doesn't exist: $opt_path"
+    tup_error 2 "layer create: path doesn't exist: $opt_path"
 fi
 
 if [[ ! -z "$opt_parent" ]] && ! parentid=$(tup refparse --layer "$opt_parent"); then
-    tup_error 2 "parent layer doesn't exist: $opt_parent"
+    tup_error 2 "layer create: parent layer doesn't exist: $opt_parent"
 fi
 
 if [[ ! -z "$opt_filesystem" ]] && ! filesystemid=$(tup refparse --filesystem "$opt_filesystem"); then
-    tup_error 2 "filesystem doesn't exist: $opt_filesystem"
+    tup_error 2 "layer create: filesystem doesn't exist: $opt_filesystem"
 fi
 
 #
@@ -118,9 +118,9 @@ tmpid=$(tup_sum_str $path $(date))
 tmpdir="$TUP_STORAGE_DIR/staging/$tmpid"
 
 if ! (mkdir -p "$tmpdir"); then
-    tup_error 3 "failed to create temporary layer directory: $tmpdir"
+    tup_error 3 "layer create: failed to create temporary layer directory: $tmpdir"
 fi
-tup_debug 1 "created temporary layer directory $tmpdir"
+tup_debug 1 "layer create: created temporary layer directory $tmpdir"
 
 
 #
@@ -134,32 +134,32 @@ if [[ ! -z "$opt_path" ]]; then
 
         plain)
             if ! (cp -rp "$opt_path" "$tmpdir/fs"); then
-                tup_error 3 "error: failed to copy path: $opt_path"
+                tup_error 3 "layer create: failed to copy path: $opt_path"
             fi
-            tup_debug 1 "copied $opt_path to $tmpdir/fs"
+            tup_debug 1 "layer create: copied $opt_path to $tmpdir/fs"
             filesytemid=$(tup_sum_dir "$tmpdir/fs")
             ;;
 
         squashfs)
-            tup_debug 2 "mksquashfs $opt_path $tmpdir/fs -no-progress $opt_squashfs_opts"
+            tup_debug 2 "layer create: mksquashfs $opt_path $tmpdir/fs -no-progress $opt_squashfs_opts"
             if ! (mksquashfs "$opt_path" "$tmpdir/fs" -no-progress $opt_squashfs_opts 2>&1 >/dev/null); then
-                tup_error 3 "failed to create squashfs from path: $opt_path"
+                tup_error 3 "layer create: failed to create squashfs from path: $opt_path"
             fi
-            tup_debug 1 "created squashfs from $opt_path"
+            tup_debug 1 "layer create: created squashfs from $opt_path"
             filesystemid=$(tup_sum_file "$tmpdir/fs")
             ;;
 
         tgz)
-            tup_debug 2 "tar czf $tmpdir/fs --acls --xattrs $opt_tar_opts $opt_path"
+            tup_debug 2 "layer create: tar czf $tmpdir/fs --acls --xattrs $opt_tar_opts $opt_path"
             if ! (tar czf "$tmpdir/fs" --acls --xattrs $opt_tar_opts "$opt_path" 2>&1 >/dev/null); then
-                tup_error 3 "failed to create tarball from path: $opt_path"
+                tup_error 3 "layer create: failed to create tarball from path: $opt_path"
             fi
-            tup_debug 1 "create tarball from $opt_path"
+            tup_debug 1 "layer create: create tarball from $opt_path"
             filesystemid=$(tup_sum_file "$tmpdir/fs")
             ;;
 
         *)
-            tup_error 1 "invalid format specified: $format"
+            tup_error 1 "layer create: invalid format specified: $format"
             ;;
 
     esac
@@ -178,33 +178,33 @@ if [[ ! -z "$parentid" ]]; then
 fi
 
 if ! (tup refparse --filesystem "$filesystemid"); then
-    tup_debug 1 "creating filesystem $filesystemid"
+    tup_debug 1 "layer create: creating filesystem $filesystemid"
 
     fsdir="$TUP_STORAGE_DIR/filesystems/$(tup_path "$filesystemid")"
     if ! (mkdir -p "$(dirname "$fsdir")"); then
-        tup_error 3 "failed to create filesystem dir $(dirname $fsdir)"
+        tup_error 3 "layer create: failed to create filesystem dir $(dirname $fsdir)"
     fi
     if ! (mv "$tmpdir/fs" "$fsdir"); then
-        tup_error 3 "failed to create filesystem: $filesystemid"
+        tup_error 3 "layer create: failed to create filesystem: $filesystemid"
     fi
 else
-    tup_debug 1 "using existing filesystem $filesystemid"
+    tup_debug 1 "layer create: using existing filesystem $filesystemid"
 fi
 
 layerid=$(tup_sum_dir "$tmpdir")
-tup_debug 1 "calculated layer checksum $layerid"
+tup_debug 1 "layer create: calculated layer checksum $layerid"
 
 path=$(tup_path $layerid)
 pdir=$(dirname $path);
 
 if ! (mkdir -p "$TUP_STORAGE_DIR/layers/$pdir"); then
-    tup_error 3 "failed to create layer parent directory: $TUP_STORAGE_DIR/layers/$pdir"
+    tup_error 3 "layer create: failed to create layer parent directory: $TUP_STORAGE_DIR/layers/$pdir"
 fi
 
 if ! (mv "$tmpdir" "$TUP_STORAGE_DIR/layers/$pdir/$layerid"); then
-    tup_error 3 "failed to create layer directory $TUP_STORAGE_DIR/layers/$path"
+    tup_error 3 "layer create: failed to create layer directory $TUP_STORAGE_DIR/layers/$path"
 fi
-tup_debug 1 "moved $tmpdir to $TUP_STORAGE_DIR/layers/$path"
+tup_debug 1 "layer create: moved $tmpdir to $TUP_STORAGE_DIR/layers/$path"
 
 if [[ -t 1 ]]; then
     echo -n "created layer "
diff --git a/lib/layer/destroy b/lib/layer/destroy
--- a/lib/layer/destroy
+++ b/lib/layer/destroy
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer destroy: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -67,11 +67,11 @@ fi
 #
 
 if ! layerid=$(tup refparse --layer "$ref"); then
-    tup_error 2 "layer doesn't exist: $ref" >&2
+    tup_error 2 "layer destroy: layer doesn't exist: $ref" >&2
 fi
 
 if ! (rm -r "$TUP_STORAGE_DIR/layers/$(tup_path $layerid)"); then
-    tup_error 3 "failed to destroy layer: $layerid"
+    tup_error 3 "layer destroy: failed to destroy layer: $layerid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/layer/lineage b/lib/layer/lineage
--- a/lib/layer/lineage
+++ b/lib/layer/lineage
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer lineage: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -73,8 +73,7 @@ fi
 #
 
 if ! layerid=$(tup refparse --layer "$ref"); then
-    echo "error: layer doesn't exist: $ref" >&2
-    exit 2
+    tup_error 2  "layer lineage: layer doesn't exist: $ref"
 fi
 
 
diff --git a/lib/layer/list b/lib/layer/list
--- a/lib/layer/list
+++ b/lib/layer/list
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer list: can't locate common.inc" >&2
     exit 1
 fi
 
diff --git a/lib/layer/mount b/lib/layer/mount
--- a/lib/layer/mount
+++ b/lib/layer/mount
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer mount: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -69,7 +69,7 @@ fi
 #
 
 if ! layerid=$(tup refparse --layer "$ref"); then
-    tup_error 2 "layer doesn't exist: $ref"
+    tup_error 2 "layer mount: layer doesn't exist: $ref"
 fi
 
 
@@ -83,21 +83,21 @@ if [[ $opt_lineage = 1 ]]; then
     layers=($(tup layer lineage $layerid --long-id --reverse))
 fi
 
-tup_debug 2 "mounting layers: ${layers[@]}"
+tup_debug 2 "layer mount: mounting layers: ${layers[@]}"
 
 for lid in ${layers[@]}; do
-    tup_debug 3 "mounting layer: $lid"
+    tup_debug 3 "layer mount: mounting layer: $lid"
     filesystemid=$(tup_conf get layer $lid filesystem)
     format=$(tup_conf get layer $lid format)
 
-    tup_debug 2 "running tup volume create --filesystem $filesystemid --$format --layer $layerid"
+    tup_debug 2 "layer mount: running tup volume create --filesystem $filesystemid --$format --layer $layerid"
     volumeid=$(tup volume create --filesystem $filesystemid --$format --layer $layerid) || { \
         rtn=$?
-        tup_debug 3 "tup volume create returned $rtn"
+        tup_debug 3 "layer mount: tup volume create returned $rtn"
         case $rtn in
             0) ;;
             100) ;;
-            *) tup_error 4 "failed to mount layer: $layerid" ;;
+            *) tup_error 4 "layer mount: failed to mount layer: $layerid" ;;
         esac
     }
 
diff --git a/lib/layer/squash b/lib/layer/squash
--- a/lib/layer/squash
+++ b/lib/layer/squash
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer squash: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -71,21 +71,21 @@ if [[ $ref = *".."* ]]; then
 
     refs=(${ref/../ })
 
-    tup_debug 1 "merging related layers from ${refs[0]} to ancestor ${refs[1]}"
+    tup_debug 1 "layer squash: merging related layers from ${refs[0]} to ancestor ${refs[1]}"
 
-    tup_debug 3 "tup refparse --layer ${refs[0]}"
+    tup_debug 3 "layer squash: tup refparse --layer ${refs[0]}"
     if ! current_layerid=$(tup refparse --layer "${refs[0]}"); then
-        tup_error 2 "layer doesn't exist: ${refs[0]}"
+        tup_error 2 "layer squash: layer doesn't exist: ${refs[0]}"
     fi
 
-    tup_debug 3 "tup refparse --layer ${refs[0]}"
+    tup_debug 3 "layer squash: tup refparse --layer ${refs[0]}"
     if ! ancestor_layerid=$(tup refparse --layer "${refs[1]}"); then
-        tup_error 2 "ancestor layer doesn't exist: ${refs[1]}"
+        tup_error 2 "layer squash: ancestor layer doesn't exist: ${refs[1]}"
     fi
 
-    tup_debug 3 "tup layer lineage $current_layerid --long-id"
+    tup_debug 3 "layer squash: tup layer lineage $current_layerid --long-id"
     if ! lineage=$(tup layer lineage $current_layerid --long-id); then
-        tup_error 4 "failed to get lineage of layer: $current_layerid"
+        tup_error 4 "layer squash: failed to get lineage of layer: $current_layerid"
     fi
 
     matched=0
@@ -98,17 +98,17 @@ if [[ $ref = *".."* ]]; then
     done
 
     if [[ $matched = 0 ]]; then
-        tup_error 2 "${refs[1]} is not an ancestor of ${refs[0]}"
+        tup_error 2 "layer squash: ${refs[1]} is not an ancestor of ${refs[0]}"
     fi
 
 else
 
-    tup_debug 1 "merging unlreated layers ${tup_getopt_posargs[@]}"
+    tup_debug 1 "layer squash: merging unrelated layers ${tup_getopt_posargs[@]}"
 
     for ref in ${tup_getopt_posargs[@]}; do
 
         if ! layerid=$(tup refparse --layer "$ref"); then
-            tup_error 2 "layer doesn't exist: $ref"
+            tup_error 2 "layer squash: layer doesn't exist: $ref"
         fi
 
         layers=(${layers[@]} $layerid)
@@ -124,16 +124,16 @@ fi
 
 for l in ${layers[@]}; do
     if ! (tup layer mount $l); then
-        tup_error 3 "failed to mount layer: $l"
+        tup_error 3 "layer squash: failed to mount layer: $l"
     fi
 done
 
 if ! volumeid=$(echo ${layers[@]} | tup volume unify --stdin --read-only); then
-    tup_error 3 "failed to create union mount"
+    tup_error 3 "layer squash: failed to create union mount"
 fi
 
 if ! layerid=$(tup volume commit $volumeid); then
-    tup_error 3 "failed to commit volume: $volumeid"
+    tup_error 3 "layer squash: failed to commit volume: $volumeid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/layer/verify b/lib/layer/verify
--- a/lib/layer/verify
+++ b/lib/layer/verify
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: layer verify: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -71,7 +71,7 @@ fi
 #
 
 if ! layerid=$(tup refparse --layer "$ref"); then
-    tup_error 2 "layer doesn't exist: $ref"
+    tup_error 2 "layer verify: layer doesn't exist: $ref"
 fi
 
 
@@ -96,20 +96,18 @@ while [[ ! -z "$layerid" ]]; do
         plain) sum=$(tup_sum_dir "$fsdir") ;;
         squashfs) sum=$(tup_sum_file "$fsdir") ;;
         tgz) sum=$(tup_sum_file "$fsdir") ;;
-        *) tup_error 2 "invalid format for layer: $layerid" ;;
+        *) tup_error 2 "layer verify: invalid format for layer: $layerid" ;;
 
     esac
 
     if [[ ! $sum = $filesystemid ]]; then
-        echo "$outid failed (filesystem: expected $filesystem, got $sum)"
-        exit 1
+        tup_error 1 "layer verify: $outid failed (filesystem: expected $filesystem, got $sum)"
     fi
-    tup_debug 1 "verified filesystem $filesystemid"
+    tup_debug 1 "layer verify: verified filesystem $filesystemid"
 
     fullsum=$(tup_sum_dir "$dir")
     if [[ ! $fullsum = $layerid ]]; then
-        echo "$outid failed (expected $layerid, got $fullsum)"
-        exit 1
+        tup_error 1 "layer verify: $outid failed (expected $layerid, got $fullsum)"
     fi
 
     echo "$outid ok"
diff --git a/lib/volume/commit b/lib/volume/commit
--- a/lib/volume/commit
+++ b/lib/volume/commit
@@ -10,14 +10,14 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: volume commit: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    tup_debug 1 "cleaning up"
+    tup_debug 1 "volume commit: cleaning up"
     if [[ ! -z "$tmpdir" && -d "$tmpdir" ]]; then
         rm -r "$tmpdir" 2>&1 >/dev/null
     fi
@@ -34,11 +34,11 @@ _usage() {
 
 usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --plain | --squashfs | --tgz ] [ --labels <label>,... | --extra-labels >label>,... ] [ --help ]
 
-Mount a volume.
+Commit the changes in a volume.
 
 Arguments:
 
-    ref             The ID of the colume to commit
+    ref             The ID of the volume to commit
 
     --help          Print usage information
     --extra-labels  Additional labels for the layer
@@ -86,11 +86,11 @@ fi
 #
 
 if ! volumeid=$(tup refparse --volume "$ref"); then
-    tup_error 2 "volume doesn't exist: $ref"
+    tup_error 2 "volume commit: volume doesn't exist: $ref"
 fi
 
 if [[ ! -z "$opt_extra_labels" && ! -z "$opt_labels" ]]; then
-    tup_error 2 "only one of --extra-labels and --labels must be specified"
+    tup_error 2 "volume commit: only one of --extra-labels and --labels must be specified"
 fi
 
 
@@ -117,7 +117,7 @@ fi
 
 vdir="$TUP_STORAGE_DIR/volumes/$(tup_path $volumeid)"
 if ! layerid=$(tup layer create --path "$vdir/mount" --$format $labels $parent); then
-    tup_error 4 "failed to commit volume: $volumeid"
+    tup_error 4 "volume commit: failed to commit volume: $volumeid"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/volume/create b/lib/volume/create
--- a/lib/volume/create
+++ b/lib/volume/create
@@ -10,14 +10,14 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: volume create: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    tup_debug 1 "cleaning up"
+    tup_debug 1 "volume create: cleaning up"
     if [[ ! -z "$tmpdir" && -d "$tmpdir" ]]; then
         rm -r "$tmpdir" 2>&1 >/dev/null
     fi
@@ -90,12 +90,12 @@ fi
 #
 
 if [[ -z "$opt_filesystem"  && ! $format = "empty" && ! -d "$source" && ! -f "$source" ]]; then
-    tup_error 2 "source doesn't exist: $source"
+    tup_error 2 "volume create: source doesn't exist: $source"
 fi
 
 if [[ ! -z $opt_filesystem ]]; then 
     if ! filesystemid=$(tup refparse --filesystem "$source"); then
-        tup_error 2 "filesystem doesn't exist: $source"
+        tup_error 2 "volume create: filesystem doesn't exist: $source"
     fi
     source="$TUP_STORAGE_DIR/filesystems/$(tup_path $filesystemid)"
 fi
@@ -108,7 +108,7 @@ if  [[ $format = "empty" ]]; then
 fi
 
 if [[ ! -z "$opt_layer" ]] && ! layerid=$(tup refparse --layer "$opt_layer"); then
-    tup_error 2 "layer doesn't exist: $opt_layer"
+    tup_error 2 "volume create: layer doesn't exist: $opt_layer"
 fi
 
 vdir="$TUP_STORAGE_DIR/volumes/$(tup_path "$volumeid")"
@@ -118,7 +118,7 @@ if [[ -d "$vdir" ]]; then
         echo -n "existing volume "
     fi
     echo $volumeid
-    tup_warn 100 "volume is already mounted: $volumeid"
+    tup_warn 100 "volume create: volume is already mounted: $volumeid"
 fi
 
 #
@@ -127,7 +127,7 @@ fi
 
 tmpdir="$TUP_STORAGE_DIR/staging/$(tup_path $volumeid)"
 if ! (mkdir -p "$tmpdir"); then
-    tup_error 4 "failed to create staging directory: $tmpdir"
+    tup_error 4 "volume create: failed to create staging directory: $tmpdir"
 fi
 
 target="$tmpdir/mount"
@@ -135,39 +135,39 @@ case $format in
 
     empty)
         if ! (mkdir -p "$target"); then
-            tup_error 3 "failed to create empty mount"
+            tup_error 3 "volume create: failed to create empty mount"
         fi
         ;;
 
     plain)
         if ! (cp -rp "$source" "$target"); then
-            tup_error 3 "failed to copy source: $source"
+            tup_error 3 "volume create: failed to copy source: $source"
         fi
-        tup_debug 1 "copied $source to $target"
+        tup_debug 1 "volume create: copied $source to $target"
         ;;
 
     squashfs)
         if ! (mkdir "$target"); then
-            tup_error 3 "failed to create volume directory: $target"
+            tup_error 3 "volume create: failed to create volume directory: $target"
         fi
         if ! (mount -t squashfs "$source" "$target" 2>&1 >/dev/null); then
-            tup_error 3 "failed to mount squashfs: $source in $target"
+            tup_error 3 "volume create: failed to mount squashfs: $source in $target"
         fi
-        tup_debug 1 "mounted squashfs $source in $target"
+        tup_debug 1 "volume create: mounted squashfs $source in $target"
         ;;
 
     tgz)
         if ! (mkdir "$target"); then
-            tup_error 3 "failed to create volume directory: $target"
+            tup_error 3 "volume create: failed to create volume directory: $target"
         fi
         if ! (tar -C "$target" -xzf "$source" 2>&1 >/dev/null); then
-            tup_error 3 "failed to extract tarball from source: $source"
+            tup_error 3 "volume create: failed to extract tarball from source: $source"
         fi
-        tup_debug 1 "extracted tarball $source to $target"
+        tup_debug 1 "volume create: extracted tarball $source to $target"
         ;;
 
     *)
-        tup_error 1 "invalid format specified: $format"
+        tup_error 1 "volume create: invalid format specified: $format"
         ;;
 
 esac
@@ -188,12 +188,12 @@ if [[ ! -z "$layerid" ]]; then
 fi
 
 if ! (mkdir -p "$(dirname "$vdir")"); then
-    tup_error 4 "failed to create volume directory: $vdir"
+    tup_error 4 "volume create: failed to create volume directory: $vdir"
 fi
-tup_debug 1 "created volume directory $vdir"
+tup_debug 1 "volume create: created volume directory $vdir"
 
 if ! (mv "$tmpdir" "$(dirname "$vdir")"); then
-    tup_error 4 "failed to move staging directory: $tmpdir"
+    tup_error 4 "volume create: failed to move staging directory: $tmpdir"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/volume/destroy b/lib/volume/destroy
--- a/lib/volume/destroy
+++ b/lib/volume/destroy
@@ -10,7 +10,7 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: volume destroy: can't locate common.inc" >&2
     exit 1
 fi
 
@@ -67,7 +67,7 @@ fi
 #
 
 if ! volumeid=$(tup refparse --volume "$ref"); then
-    tup_error 2 "volume doesn't exist: $volumeid"
+    tup_error 2 "volume destroy: volume doesn't exist: $volumeid"
 fi
 
 format=$(tup_conf get volume $volumeid format)
@@ -81,8 +81,8 @@ case $format in
         msg=$(umount "$path" 2>&1 >/dev/null) || \
         case $? in
             0) ;;
-            32) tup_debug 2 "overlayfs volume not mounted: $volumeid" ;;
-            *) tup_error 3 "failed to unmount overlayfs: ($code) $path" ;;
+            32) tup_debug 2 "volume destroy: overlayfs volume not mounted: $volumeid" ;;
+            *) tup_error 3 "volume destroy: failed to unmount overlayfs: ($code) $path" ;;
         esac
         ;;
 
@@ -93,8 +93,8 @@ case $format in
         msg=$(umount "$path" 2>&1 >/dev/null) || \
         case $? in
             0) ;;
-            32) tup_debug 2 "squashfs volume not mounted: $volumeid" ;;
-            *) tup_error 3 "failed to unmount squashfs: ($code) $path" ;;
+            32) tup_debug 2 "volume destroy: squashfs volume not mounted: $volumeid" ;;
+            *) tup_error 3 "volume destroy: failed to unmount squashfs: ($code) $path" ;;
         esac
         ;;
 
@@ -102,13 +102,13 @@ case $format in
         ;;
 
     *)
-        tup_error 2 "unknown format specified: $format"
+        tup_error 2 "volume destroy: unknown format specified: $format"
         ;;
 
 esac
 
 if ! (rm -r "$(dirname "$path")"); then
-    tup_error 3 "failed to remove volume directory: $path"
+    tup_error 3 "volume destroy: failed to remove volume directory: $path"
 fi
 
 if [[ -t 1 ]]; then
diff --git a/lib/volume/unify b/lib/volume/unify
--- a/lib/volume/unify
+++ b/lib/volume/unify
@@ -10,14 +10,14 @@
 set -e
 
 if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
-    echo "error: can't locate common.inc" >&2
+    echo "error: volume unify: can't locate common.inc" >&2
     exit 1
 fi
 
 . "$TUP_LIB_DIR/includes/common.inc"
 
 _cleanup() {
-    tup_debug 1 "cleaning up"
+    tup_debug 1 "volume unify: cleaning up"
     if [[ ! -z "$voldir" && -d "$voldir" ]]; then
         rm -r "$voldir" 2>&1 >/dev/null
     fi
@@ -79,7 +79,7 @@ fi
 #
 
 if [[ -z $opt_stdin && ${#tup_getopt_posargs[@]} = 0 ]]; then
-    tup_error 2 "no volumes specified"
+    tup_error 2 "volume unify: no volumes specified"
 fi
 
 
@@ -91,24 +91,24 @@ volumes=()
 volids=()
 
 if [[ $opt_stdin = 1 ]]; then
-    tup_debug 1 "reading volumes from stdin"
+    tup_debug 1 "volume unify: reading volumes from stdin"
     while read id; do
         if ! volid=$(tup refparse --volume "$id"); then
-            tup_error 2 "volume doesn't exist: $id"
+            tup_error 2 "volume unify: volume doesn't exist: $id"
         fi
-        tup_debug 3 "using volume $volid"
+        tup_debug 3 "volume unify: found volume $volid"
         volumes=("${volumes[@]}" "$TUP_STORAGE_DIR/volumes/$(tup_path $volid)/mount")
         volids=(${volids[@]} $volid)
     done
 else
-    tup_debug 1 "reading volumes from command line"
+    tup_debug 1 "volume unify: reading volumes from command line"
     i=0
     while [[ ! -z ${tup_getopt_posargs[$i]} ]]; do
         id=${tup_getopt_posargs[$i]}
         if ! volid=$(tup refparse --volume "$id"); then
-            tup_error 2 "volume doesn't exist: $id"
+            tup_error 2 "volume unify: volume doesn't exist: $id"
         fi
-        tup_debug 3 "using volume $volid"
+        tup_debug 3 "volume unify: found volume $volid"
         volumes=("${volumes[@]}" "$TUP_STORAGE_DIR/volumes/$(tup_path $volid)/mount")
         volids=(${volids[@]} $volid)
         let i=i+1
@@ -118,19 +118,23 @@ fi
 volumeid=$(tup_sum_str "${volumes[@]}")
 voldir="$TUP_STORAGE_DIR/volumes/$(tup_path $volumeid)"
 
-tup_debug 2 "using volume ID $volumeid"
+tup_debug 2 "volume unify: generated unified volume ID $volumeid"
 
 if [[ -d "$voldir" ]]; then
     voldir=""
-    tup_error 2 "volume already exists: $volumeid"
+    if [[ -t 1 ]]; then
+        echo -n "already unified as "
+    fi
+    echo $volumeid
+    tup_warn 100 "volume unify: volume already mounted: $volumeid"
 fi
 
 if ! (mkdir -p "$voldir/.overlayfs"); then
-    tup_error 4 "failed to create volume directory: $voldir"
+    tup_error 4 "volume unify: failed to create volume directory: $voldir"
 fi
 
 if ! (mkdir "$voldir/mount"); then
-    tup_error 4 "failed to create mount point: $voldir/mount"
+    tup_error 4 "volume unify: failed to create mount point: $voldir/mount"
 fi
 
 lowerdir=""
@@ -142,10 +146,10 @@ len=${#volumes[@]}
 while [[ $i -lt $len ]]; do
     let next=i+1
     if [[ $next = $len && $opt_read_write = 1 ]]; then
-        tup_debug 2 "upperdir ${volumes[$i]}"
+        tup_debug 2 "volume unify: upperdir ${volumes[$i]}"
         upperdir=${volumes[$i]}
     else
-        tup_debug 2 "lowerdir ${volumes[$i]}"
+        tup_debug 2 "volume unify: lowerdir ${volumes[$i]}"
         if [[ ! -z $lowerdir ]]; then
             lowerdir="$lowerdir:"
         fi
@@ -161,7 +165,7 @@ if [[ ! -z $upperdir ]]; then
 fi
 
 if ! (mount -t overlay overlay -o $opts "$voldir/mount" 2>&1 >/dev/null); then
-    tup_error 3 "failed to mount overlayfs: $opts"
+    tup_error 3 "volume unify: failed to mount overlayfs: $opts"
 fi
 
 touch "$voldir/conf"
